// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBddwZKkPQSa5XJiEv7FhDni7xakKQL90M',
    appId: '1:419830140116:web:a62d51cce842fadd817f41',
    messagingSenderId: '419830140116',
    projectId: 'bonafide-a5389',
    authDomain: 'bonafide-a5389.firebaseapp.com',
    storageBucket: 'bonafide-a5389.firebasestorage.app',
    measurementId: 'G-42NW9BJ5D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeoe-gAnZJN_iqlQjL6atxNMsP6lvv2vU',
    appId: '1:419830140116:android:7bc64361c9719704817f41',
    messagingSenderId: '419830140116',
    projectId: 'bonafide-a5389',
    storageBucket: 'bonafide-a5389.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqNMoMl2NXb8IAYVzBRzrbd9lYqU34dds',
    appId: '1:419830140116:ios:644f822ffb461e6c817f41',
    messagingSenderId: '419830140116',
    projectId: 'bonafide-a5389',
    storageBucket: 'bonafide-a5389.firebasestorage.app',
    iosBundleId: 'com.example.bonafideMad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqNMoMl2NXb8IAYVzBRzrbd9lYqU34dds',
    appId: '1:419830140116:ios:644f822ffb461e6c817f41',
    messagingSenderId: '419830140116',
    projectId: 'bonafide-a5389',
    storageBucket: 'bonafide-a5389.firebasestorage.app',
    iosBundleId: 'com.example.bonafideMad',
  );
}
